# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_tabs.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        MainWindow.setFont(font)
        MainWindow.setAccessibleName("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_general_open = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_general_open.setObjectName("pushButton_general_open")
        self.gridLayout.addWidget(self.pushButton_general_open, 0, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.gridLayout.addItem(spacerItem, 0, 2, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_0 = QtWidgets.QWidget()
        self.tab_0.setObjectName("tab_0")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.gridLayout_2.addItem(spacerItem1, 5, 5, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.gridLayout_2.addItem(spacerItem2, 2, 7, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(
            20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed
        )
        self.gridLayout_2.addItem(spacerItem3, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.tab_0)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignBottom | QtCore.Qt.AlignHCenter)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 4, 1, 1, 1)
        self.dateTimeEdit_to = QtWidgets.QDateTimeEdit(self.tab_0)
        self.dateTimeEdit_to.setObjectName("dateTimeEdit_to")
        self.gridLayout_2.addWidget(self.dateTimeEdit_to, 5, 2, 1, 3)
        self.dateTimeEdit_from = QtWidgets.QDateTimeEdit(self.tab_0)
        self.dateTimeEdit_from.setCalendarPopup(True)
        self.dateTimeEdit_from.setObjectName("dateTimeEdit_from")
        self.gridLayout_2.addWidget(self.dateTimeEdit_from, 5, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.gridLayout_2.addItem(spacerItem4, 2, 0, 1, 1)
        self.pushButton_open = QtWidgets.QPushButton(self.tab_0)
        self.pushButton_open.setObjectName("pushButton_open")
        self.gridLayout_2.addWidget(self.pushButton_open, 2, 6, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(
            20, 120, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding
        )
        self.gridLayout_2.addItem(spacerItem5, 9, 2, 1, 1)
        self.lineEdit_filepath = QtWidgets.QLineEdit(self.tab_0)
        self.lineEdit_filepath.setMinimumSize(QtCore.QSize(360, 0))
        self.lineEdit_filepath.setObjectName("lineEdit_filepath")
        self.gridLayout_2.addWidget(self.lineEdit_filepath, 2, 1, 1, 5)
        self.label_3 = QtWidgets.QLabel(self.tab_0)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignBottom | QtCore.Qt.AlignHCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 4, 6, 1, 1)
        self.comboBox_pattern = QtWidgets.QComboBox(self.tab_0)
        self.comboBox_pattern.setMinimumSize(QtCore.QSize(95, 0))
        self.comboBox_pattern.setObjectName("comboBox_pattern")
        self.gridLayout_2.addWidget(self.comboBox_pattern, 5, 6, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(
            20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed
        )
        self.gridLayout_2.addItem(spacerItem6, 3, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.tab_0)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignBottom | QtCore.Qt.AlignHCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 4, 3, 1, 1)
        self.pushButton_raw = QtWidgets.QPushButton(self.tab_0)
        self.pushButton_raw.setObjectName("pushButton_raw")
        self.gridLayout_2.addWidget(self.pushButton_raw, 6, 6, 1, 1)
        self.pushButton_analyze = QtWidgets.QPushButton(self.tab_0)
        self.pushButton_analyze.setObjectName("pushButton_analyze")
        self.gridLayout_2.addWidget(self.pushButton_analyze, 8, 1, 1, 6)
        self.tabWidget.addTab(self.tab_0, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.tab_4)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_4 = QtWidgets.QLabel(self.tab_4)
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(70)
        font.setBold(False)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setWordWrap(False)
        self.label_4.setObjectName("label_4")
        self.gridLayout_6.addWidget(self.label_4, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_4, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.widget = QtWidgets.QWidget(self.tab)
        self.widget.setObjectName("widget")
        self.gridLayout_3.addWidget(self.widget, 0, 0, 1, 4)
        self.comboBox_0 = QtWidgets.QComboBox(self.tab)
        self.comboBox_0.setObjectName("comboBox_0")
        self.gridLayout_3.addWidget(self.comboBox_0, 1, 0, 1, 1)
        self.comboBox_2 = QtWidgets.QComboBox(self.tab)
        self.comboBox_2.setObjectName("comboBox_2")
        self.gridLayout_3.addWidget(self.comboBox_2, 1, 3, 1, 1)
        self.comboBox_1 = QtWidgets.QComboBox(self.tab)
        self.comboBox_1.setEditable(True)
        self.comboBox_1.setObjectName("comboBox_1")
        self.gridLayout_3.addWidget(self.comboBox_1, 1, 1, 1, 2)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.widget_2 = QtWidgets.QWidget(self.tab_2)
        self.widget_2.setObjectName("widget_2")
        self.gridLayout_4.addWidget(self.widget_2, 1, 0, 1, 1)
        self.checkBox_0 = QtWidgets.QCheckBox(self.tab_2)
        self.checkBox_0.setObjectName("checkBox_0")
        self.gridLayout_4.addWidget(self.checkBox_0, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.tableView = QtWidgets.QTableView(self.tab_3)
        self.tableView.setObjectName("tableView")
        self.gridLayout_5.addWidget(self.tableView, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_3, "")
        self.gridLayout.addWidget(self.tabWidget, 1, 1, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_general_open.setText(_translate("MainWindow", "Open File"))
        self.label.setText(_translate("MainWindow", "From"))
        self.pushButton_open.setText(_translate("MainWindow", "Open"))
        self.label_3.setText(_translate("MainWindow", "Pattern"))
        self.label_2.setText(_translate("MainWindow", "To"))
        self.pushButton_raw.setText(_translate("MainWindow", "View RAW"))
        self.pushButton_analyze.setText(_translate("MainWindow", "Analyze"))
        self.tabWidget.setTabText(
            self.tabWidget.indexOf(self.tab_0), _translate("MainWindow", "Open File")
        )
        self.label_4.setText(_translate("MainWindow", "Hello"))
        self.tabWidget.setTabText(
            self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Page")
        )
        self.tabWidget.setTabText(
            self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Summary")
        )
        self.checkBox_0.setText(_translate("MainWindow", "GroupBy"))
        self.tabWidget.setTabText(
            self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Statistic")
        )
        self.tabWidget.setTabText(
            self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "RAW")
        )


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
